### ISSUE TITLE
backend TkAgg version unknown

### ISSUE THREAD

**Issue by a83912a** [fabiocarrara/deep-parking#14]
Hello Fabiocarrara, thank you for providing this project for everyone to try. At present, I have encountered a problem. I have an error after executing pklot.py. I also have this problem in main.py.

I also found debug information in the log, did not see any errors, only matplotlib will have a debug when just executed, how can this be solved?

matplotlib       version         2.2.3

**_DEBUG 2019-02-11 00:28:43: CACHEDIR=/home/user/.cache/matplotlib
DEBUG 2019-02-11 00:28:43: Using fontManager instance from /home/user/.cache/matplotlib/fontList.json
DEBUG 2019-02-11 00:28:45: backend TkAgg version unknown_**
INFO 2019-02-11 00:28:45: Setting up mAlexNet trained on PKLot_UFPR05_train, validated on PKLot_UFPR04_train, PKLot_UFPR05_train, PKLot_PUC_train, tested on PKLot_UFPR04_test_PKLot_UFPR05_test_PKLot_PUC_test ...
INFO 2019-02-11 00:28:48: Training on PKLot_UFPR05_train while validating on PKLot_UFPR04_train, PKLot_UFPR05_train, PKLot_PUC_train ...
I0211 07:58:45.212375  2009 sgd_solver.cpp:112] Iteration 26166, lr = 0.0025
I0211 07:59:24.925103  2009 solver.cpp:239] Iteration 26215 (1.23388 iter/s, 39.712s/49 iters), loss = 0.00707085
I0211 07:59:24.925237  2009 solver.cpp:258]     Train net output #0: loss = 0.00173975 (* 1 = 0.00173975 loss)
I0211 07:59:24.925256  2009 sgd_solver.cpp:112] Iteration 26215, lr = 0.0025
I0211 08:00:04.641950  2009 solver.cpp:239] Iteration 26264 (1.23376 iter/s, 39.716s/49 iters), loss = 0.00808991
I0211 08:00:04.642046  2009 solver.cpp:258]     Train net output #0: loss = 0.000425289 (* 1 = 0.000425289 loss)
I0211 08:00:04.642061  2009 sgd_solver.cpp:112] Iteration 26264, lr = 0.0025
I0211 08:00:44.350703  2009 solver.cpp:239] Iteration 26313 (1.23401 iter/s, 39.708s/49 iters), loss = 0.00666064
I0211 08:00:44.350908  2009 solver.cpp:258]     Train net output #0: loss = 0.00237676 (* 1 = 0.00237676 loss)
I0211 08:00:44.350924  2009 sgd_solver.cpp:112] Iteration 26313, lr = 0.0025
I0211 08:01:24.058185  2009 solver.cpp:239] Iteration 26362 (1.23404 iter/s, 39.707s/49 iters), loss = 0.008896
I0211 08:01:24.058348  2009 solver.cpp:258]     Train net output #0: loss = 0.00142862 (* 1 = 0.00142862 loss)
I0211 08:01:24.058367  2009 sgd_solver.cpp:112] Iteration 26362, lr = 0.0025
I0211 08:02:03.743736  2009 solver.cpp:239] Iteration 26411 (1.23472 iter/s, 39.685s/49 iters), loss = 0.003344
I0211 08:02:03.743832  2009 solver.cpp:258]     Train net output #0: loss = 0.000362561 (* 1 = 0.000362561 loss)
I0211 08:02:03.743847  2009 sgd_solver.cpp:112] Iteration 26411, lr = 0.0025
I0211 08:02:14.302935  2009 solver.cpp:464] Snapshotting to binary proto file snapshots/snapshot_iter_26425.caffemodel
I0211 08:02:14.303773  2009 sgd_solver.cpp:284] Snapshotting solver state to binary proto file snapshots/snapshot_iter_26425.solverstate
I0211 08:02:14.304250  2009 solver.cpp:332] Optimization Done.
I0211 08:02:14.304262  2009 caffe.cpp:250] Optimization Done.
**_DEBUG 2019-02-11 08:02:14: Summarizing mAlexNet-tr_PKLot_UFPR05_train-vl_PKLot_UFPR04_train_PKLot_UFPR05_train_PKLot_PUC_train-ts_PKLot_UFPR04_test_PKLot_UFPR05_test_PKLot_PUC_test ...
Traceback (most recent call last):
  File "pklot.py", line 38, in <module>
    pyffe.summarize(exps).to_csv('pklot_results.csv')
  File "/home/user/deep-parking-master/deep-parking-master/pyffe/experiment.py", line 84, in summarize
    r = e.summarize()
  File "/home/user/deep-parking-master/deep-parking-master/pyffe/experiment.py", line 42, in decorator
    return function(*args, **kwargs)
  File "/home/user/deep-parking-master/deep-parking-master/pyffe/experiment.py", line 548, in summarize
    last_iter = log_data['train']['iteration'][-1]
IndexError: list index out of range_**

Thank you

**Comment by fabiocarrara** [comment]
Hi, 
for the first problem, you should check your matplotlib installation, try google: https://stackoverflow.com/questions/13110403/matplotlib-backend-missing-modules-with-underscore

About the IndexError, this arises when trying to read an empty experiment log. Check the logs of each experiment for errors during the training phase. It might be that one or more run have failed and contain no training log data. This makes the summarize() operation fail.
