### ISSUE TITLE
Issue on import

### ISSUE THREAD

**Issue by shivalekshmi** [fabiocarrara/deep-parking#20]
Hi Fabio Carrara,
`I have already installed caffe and pyffe in  my system, but still there is import error. 
Traceback (most recent call last):
  File "pklot.py", line 1, in <module>
    import pyffe
  File "/home/shiva/deep-parking/pyffe/__init__.py", line 3, in <module>
    from .forward import forward_all
  File "/home/shiva/deep-parking/pyffe/forward.py", line 12, in <module>
    import caffe
ImportError: No module named caffe

**Comment by fabiocarrara** [comment]
Please make sure caffe with the python interface is properly installed.
